<?php
/* @var $this SSE_EditCustomOptions_Block_Link */
?>
<a href="#" id="<?php echo $this->getOptionsDivId(); ?>">Edit Custom Options</a>


<script type="text/javascript">// <![CDATA[
(function(){
	$('<?php echo $this->getOptionsDivId(); ?>').observe('click', function() {
		var url ='<?php echo $this->getPopupUrl(); ?>'
	    var win = new Window({className:'magento',title:'Configure Product Custom Options',url:url,width:820,height:600,minimizable:false,maximizable:false,showEffectOptions:{duration:0.4},hideEffectOptions:{duration:0.4}});
	    win.setZIndex(100);
	    win.showCenter(true);
	});
})();
// ]]></script>