<?php
/* @var $optionsBlock SSE_EditCustomOptions_Block_Options */
$optionsBlock = $this->getLayout()->createBlock(SSE_EditCustomOptions_Block_Options::ALIAS);
$optionsBlock->init($this->getParentBlock()->getItem());
?>
<a href="#" onclick="$('<?php echo $optionsBlock->getOptionsDivId(); ?>').show();return false;">Edit Options</a>
<div id="<?php echo $optionsBlock->getOptionsDivId() ?>" style="display:none; border: 1px solid #ccc; padding: 10px; margin-left: 10px;">
<?php
    echo $optionsBlock->toHtml();
?>
</div>